# Generated by Django 4.2.1 on 2023-05-29 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This holds the date the cart was created",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="This indicates if the cart is completed",
                        verbose_name="Date Completed",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="This holds the session ID",
                        max_length=100,
                        null=True,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the customer that owns the cart",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="This holds the name of the category",
                        max_length=200,
                        verbose_name="Category Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(default=None, help_text="This is the slug of the category", verbose_name="Slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="This is the icon of the category",
                        max_length=100,
                        null=True,
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="This is the name of the product",
                        max_length=200,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="This is a short description of the product",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "discount",
                    models.BooleanField(
                        default=False,
                        help_text="This holds if the product has a discount on it",
                        verbose_name="Discount",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Product  image for the current product, which should be in PNG, JPEG, or JPG format",
                        null=True,
                        upload_to="photos/product_image",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "old_price",
                    models.FloatField(
                        default=100.0, help_text="This holds the old price of the product", verbose_name="Old Price"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(default=None, help_text="This is the slug of the product", verbose_name="Slug"),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        default=5,
                        help_text="This is the number of products in the inventory",
                        verbose_name="Inventory",
                    ),
                ),
                (
                    "top_deal",
                    models.BooleanField(
                        default=False,
                        help_text="This indicates if the product is a top deal or not",
                        verbose_name="Top Deal",
                    ),
                ),
                (
                    "flash_sales",
                    models.BooleanField(
                        default=False,
                        help_text="This indicates if the product ison flash sales or not",
                        verbose_name="Flash Sales",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="This holds the Category the product belongs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "added",
                    models.IntegerField(
                        default=0, help_text="This holds the the numbers of added items", verbose_name="Added"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="This holds the saved product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="This holds the saved product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="category",
            name="featured_product",
            field=models.OneToOneField(
                blank=True,
                help_text="This is the product in which the category is featured",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_product",
                to="store.product",
            ),
        ),
        migrations.CreateModel(
            name="Cartitem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity",
                    models.IntegerField(default=0, help_text="This holds the cart quantity", verbose_name="Quantity"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        help_text="This holds the cart items Id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.cart",
                        verbose_name="Cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="This holds the cart products",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartitems",
                        to="store.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "home_address_1",
                    models.CharField(
                        help_text="This holds the customers address the product will be delivered to",
                        max_length=250,
                        verbose_name="Home Address 1",
                    ),
                ),
                (
                    "home_address_2",
                    models.CharField(
                        help_text="This holds the customers address the product will be delivered to",
                        max_length=250,
                        verbose_name="Home Address 2",
                    ),
                ),
                (
                    "bus_stop",
                    models.CharField(
                        blank=True,
                        help_text="This holds the bus stop the product will be delivered to",
                        max_length=100,
                        null=True,
                        verbose_name="Bus Stop",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="This holds the city the product will be delivered to",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="This holds the state the product will be delivered to",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        default="",
                        help_text="This holds the customer details of the address",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
    ]
