# Generated by Django 4.2.1 on 2023-05-30 22:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cartitem",
            new_name="Cart_Item",
        ),
        migrations.RenameModel(
            old_name="SavedItem",
            new_name="Saved_Item",
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-created_date"], "verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-created_date"], "verbose_name": "Cart", "verbose_name_plural": "Carts"},
        ),
        migrations.AlterModelOptions(
            name="cart_item",
            options={"verbose_name": "CartItem", "verbose_name_plural": "CartItems"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-created_date"], "verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_date"], "verbose_name": "Products ", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="saved_item",
            options={"ordering": ["-created_date"], "verbose_name": "Saved Item", "verbose_name_plural": "SavedItems"},
        ),
    ]
