# Generated by Django 4.2.1 on 2023-05-31 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_rename_cartitem_cart_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart_item",
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items"},
        ),
        migrations.AlterModelOptions(
            name="saved_item",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Saved Item",
                "verbose_name_plural": "Saved Items",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="old_price",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, help_text="This is the slug of the product", null=True, verbose_name="Slug"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Hold the date the review was created",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="description",
                        help_text="This holds the description of the review",
                        verbose_name="Description",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="Anonymous",
                        help_text="This field holds the name of the reviewer ",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Holds the product on reviw",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="Product_Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="This holds the Product Images",
                        null=True,
                        upload_to="photos/properties_image",
                        verbose_name="Image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="this holds the Product that Images",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Products Image",
                "verbose_name_plural": "Product Images",
            },
        ),
    ]
