# Generated by Django 4.2.1 on 2023-05-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "users  Account", "verbose_name_plural": "users  Account"},
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Holds the First name of the user.",
                max_length=200,
                verbose_name="First Name of User",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Holds the Last name of the user",
                max_length=200,
                verbose_name="Last Name of User",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The email address of the customer.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
