# Generated by Django 4.1.9 on 2023-05-26 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_name_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "users  Account", "verbose_name_plural": "users  Account"},
        ),
    ]
